### ISSUE TITLE
Error when trying to download the "sitsdata" package

### ISSUE THREAD

**Issue by kamaulindhardt** [e-sensing/sitsdata#5]
**Hi** 

I am a huge fan of your work on the SITS package. I am interested in running some of your examples but run into a problem when I try to download the package. Any idea what might be happening here..?

`devtools::install_github("e-sensing/sitsdata")`

```
Downloading GitHub repo e-sensing/sitsdata@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/e-sensing/sitsdata/tarball/HEAD' failed
```

I have also tried ´remotes::install_github("e-sensing/sitsdata")´ – no luck.. but same error message.

Best regards,
Kamau

**Comment by gilbertocamara** [comment]
Dear Kamau,
I have tried to download the "sitsdata" package in my machine using 
`devtools::install_github("e-sensing/sitsdata")`
and it worked. Could it be a network problem on your side?

**Comment by kamaulindhardt** [comment]
Good morning Gilberto, 

Thank you for your prompt response. Yes it was a network issue as I was able to download it at my university. 

Enjoy your day!

`devtools::install_github("e-sensing/sitsdata")`

```
Downloading GitHub repo e-sensing/sitsdata@HEAD
✓  checking for file ‘/private/var/folders/6p/c87kn7652k3bb9lw5j3c2rn00000gp/T/RtmpPIZCM8/remotesdfa7319b4a0c/e-sensing-sitsdata-16c8fa7/DESCRIPTION’ (425ms)
─  preparing ‘sitsdata’: (617ms)
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sitsdata_0.4.tar.gz’
   
* installing *source* package ‘sitsdata’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (sitsdata)
```
